### ISSUE TITLE
Add build and flashing instructions

### ISSUE THREAD

**Issue by kdsch** [TDHolmes/oven-temp-rs#2]
The [GitHub workflows](https://github.com/TDHolmes/oven-temp-rs/blob/master/.github/workflows/rust.yml) contain some examples of how to invoke the build system, but it would be nice to document it in the readme.

I've encountered a number of different tools for flashing and am curious what your approach is. I understand this might be pretty specific to whether a bootloader is being used; nevertheless having an example of this would be useful.

**Comment by TDHolmes** [comment]
Sure! I'll write that up. I use `cargo hf2` to flash with the boot loader Adafruit ships on most of their feather boards

**Comment by TDHolmes** [comment]
Let me know if you think anything is missing in #3
